name: Release Build

on:
  push:
    tags: ["*"]

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: bun run build

      - name: Upload graphology UMD
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/graphology/dist/graphology.umd.js
          asset_name: graphology.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload graphology UMD minified
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/graphology/dist/graphology.umd.min.js
          asset_name: graphology.min.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload graphology-library
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/library/dist/graphology-library.js
          asset_name: graphology-library.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload graphology-library minified
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./src/library/dist/graphology-library.min.js
          asset_name: graphology-library.min.js
          tag: ${{ github.ref }}
          overwrite: true
